### ISSUE TITLE
Missing glyph traceback

### ISSUE THREAD

**Issue by ryanbugden** [ryanbugden/Smooth-Operator#4]
```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 90, in sendEvent_
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/vanilla/vanillaBase.py", line 539, in action_
    self.callback(sender)
  File "main.py", line 342, in scanButtonCallback
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/SmoothOperator.roboFontExt/lib/logic.py", line 121, in scan_fonts
    f[g_name].drawPoints(check_pen) 
    ~^^^^^^^^
  File "lib/fontObjects/fontPartsWrappers.pyc", line 1904, in __getitem__
KeyError: "No glyph named 'dollar.8'."

```

**Comment by ryanbugden** [comment]
Note to self: scan for any issues on an if-it-has-this-glyph basis. Don't require all sources to have the glyph.
